#############################################################################
##
#W  automgroup.gd             automata package                 Yevgen Muntyan
#W                                                             Dmytro Savchuk
##
##  automata v0.9, started 01/22/2004
##

Revision.automgroup_gd :=
  "@(#)$Id$";


#############################################################################
##
#C  IsAutomGroup( <G> )
##
##  returns true if G is a group generated by elements from category
##  IsAutom
##
DeclareSynonym("IsAutomGroup", IsGroup and IsAutomCollection);
InstallTrueMethod(IsAutomataGroup, IsAutomGroup);


#############################################################################
##
#O  AutomGroup(<automaton_list>)
#O  AutomGroup(<automaton_list>, <names>)
#O  AutomGroupNoBindGlobal(<automaton_list>)
#O  AutomGroupNoBindGlobal(<automaton_list>, <names>)
##
DeclareOperation("AutomGroup", [IsList]);
DeclareOperation("AutomGroupNoBindGlobal", [IsList]);


#############################################################################
##
#A  UnderlyingAutomFamily(<G>)
##
DeclareAttribute("UnderlyingAutomFamily", IsAutomGroup);
InstallSubsetMaintenance(UnderlyingAutomFamily, IsCollection, IsCollection);


#############################################################################
##
#P  IsGroupOfAutomFamily(<G>)
#A  GroupOfAutomFamily(<fam>)
##
DeclareProperty("IsGroupOfAutomFamily", IsAutomGroup);
DeclareAttribute("GroupOfAutomFamily", IsAutomFamily);
InstallTrueMethod(IsSelfSimilar, IsGroupOfAutomFamily);


#############################################################################
##
#P  IsFractalByWords(<G>)
##
DeclareProperty("IsFractalByWords", IsAutomGroup);
InstallTrueMethod(IsFractal, IsFractalByWords);


#############################################################################
##
#A  MihaylovSystem(<G>)
##
DeclareAttribute("MihaylovSystem", IsAutomGroup, "mutable");


#############################################################################
##
#A  UnderlyingFreeSubgroup(<G>)
#A  UnderlyingFreeGenerators(<G>)
#A  UnderlyingFreeGroup(<G>)
##
DeclareAttribute("UnderlyingFreeSubgroup", IsAutomGroup, "mutable");
DeclareAttribute("UnderlyingFreeGenerators", IsAutomGroup, "mutable");
DeclareAttribute("UnderlyingFreeGroup", IsAutomGroup);


#############################################################################
##
#A  IndexInFreeGroup(<G>)
##
DeclareAttribute("IndexInFreeGroup", IsAutomGroup, "mutable");


#E
