name: AutomGrp
version: "1.3.1dev"
date: 2018-09-30
description: |
    Automata groups

authors:
    - name: Yevgen Muntyan
      url: mailto:muntyan@fastmail.fm
    - name: Dmytro Savchuk
      url: http://savchuk.myweb.usf.edu/

maintainers:
    - name: Yevgen Muntyan
      url: mailto:muntyan@fastmail.fm
    - name: Dmytro Savchuk
      url: http://savchuk.myweb.usf.edu/

GAP: ">=4.9.1"

needed-pkgs:
    - name: "FGA"
      version: ">= 1.1.0.1"
      url: "http://www.icm.tu-bs.de/ag_algebra/software/FGA/"

suggested-pkgs:
    - name: "FR"
      version: ">= 2.0.0"
      url: "https://gap-packages.github.io/fr"

www: http://finautom.sourceforge.net/
readme: README
packageinfo: http://finautom.sourceforge.net/automgrp/PackageInfo.g

downloads:
    - name: .tar.bz2
      url: http://sourceforge.net/projects/finautom/files/automgrp/1.3.1/automgrp-1.3.1.tar.bz2
    - name: .tar.gz
      url: http://sourceforge.net/projects/finautom/files/automgrp/1.3.1/automgrp-1.3.1.tar.gz
    - name: -win.zip
      url: http://sourceforge.net/projects/finautom/files/automgrp/1.3.1/automgrp-1.3.1-win.zip

abstract: |
    The <span class="pkgname">AutomGrp</span> package provides methods for computations with groups and semigroups generated by finite automata or given by wreath recursion, as well as with their finitely generated subgroups and elements.

status: accepted
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
keywords: |
    finite automata, tree automorphisms, self-similar groups, wreath recursion.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>MS18</span>]   <b class='BibAuthor'>Muntyan, Y. and Savchuk, D.</b>,
     <i class='BibTitle'>AutomGrp, Automata groups,
             Version 1.3.1dev</i>
     (<span class='BibYear'>2018</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="http://finautom.sourceforge.net/">http://finautom.sourceforge.net/</a></span>.
    </p>
    

bibtex: |
    @misc{ AutomGrp1.3.1dev,
      author =           {Muntyan, Y. and Savchuk, D.},
      title =            {{AutomGrp}, Automata groups, {V}ersion 1.3.1dev},
      month =            {Sep},
      year =             {2018},
      note =             {Refereed GAP package},
      howpublished =     {\href {http://finautom.sourceforge.net/} {\texttt{http://finautom.sourceforge.net/}}},
      keywords =         {finite automata; tree automorphisms; self-similar groups; wreath recursion},
      printedkey =       {MS18}
    }

