name: AutomGrp
version: "1.3.3"
license: "MIT"
date: 2025-01-08
description: |
    Automata groups

authors:
    - name: Yevgen Muntyan
      url: mailto:muntyan@fastmail.fm
    - name: Dmytro Savchuk
      url: http://savchuk.myweb.usf.edu/

maintainers:
    - name: Yevgen Muntyan
      url: mailto:muntyan@fastmail.fm
    - name: Dmytro Savchuk
      url: http://savchuk.myweb.usf.edu/

GAP: ">=4.9.1"

needed-pkgs:
    - name: "FGA"
      version: ">= 1.1.0.1"
      url: "https://gap-packages.github.io/fga/"

suggested-pkgs:
    - name: "FR"
      version: ">= 2.0.0"
      url: "https://gap-packages.github.io/fr"

www: https://gap-packages.github.io/automgrp
readme: README.md
packageinfo: https://gap-packages.github.io/automgrp/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/automgrp/releases/download/v1.3.3/automgrp-1.3.3.tar.gz
    - name: .tar.bz2
      url: https://github.com/gap-packages/automgrp/releases/download/v1.3.3/automgrp-1.3.3.tar.bz2

abstract: |
    The <span class="pkgname">AutomGrp</span> package provides methods for computations with groups and semigroups generated by finite automata or given by wreath recursion, as well as with their finitely generated subgroups and elements.

status: accepted
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
keywords: |
    finite automata, tree automorphisms, self-similar groups, wreath recursion.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>MS25</span>]   <b class='BibAuthor'>Muntyan, Y. and Savchuk, D.</b>,
     <i class='BibTitle'>AutomGrp, Automata groups,
             Version 1.3.3</i>
     (<span class='BibYear'>2025</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/automgrp">https://gap-packages.github.io/automgrp</a></span>.
    </p>
    

bibtex: |
    @misc{ AutomGrp,
      author =           {Muntyan, Y. and Savchuk, D.},
      title =            {{AutomGrp}, {Automata groups}, {V}ersion 1.3.3},
      month =            {Jan},
      year =             {2025},
      note =             {GAP package},
      howpublished =     {\href        {https://gap-packages.github.io/automgrp}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{automgrp}}},
      keywords =         {finite       automata;       tree       automorphisms;
                          self\texttt{\symbol{45}}similar     groups;     wreath
                          recursion},
      printedkey =       {MS25}
    }

