# AutomGrp, chapter 5
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("automgrp05.tst");

# doc/../gap/convertersfr.gd:22-29
gap> FZ := FRGroup("t=<,t>[2,1]");
<state-closed group over [ 1 .. 2 ] with 1 generator>
gap> AZ := FR2AutomGrp(FZ);
< t >
gap> Display(AZ);
< t = (1, t)(1,2) >

# doc/../gap/convertersfr.gd:30-39
gap> i4 := FRMonoid("s=(1,2)","f=<s,f>[1,1]");
<state-closed monoid over [ 1 .. 2 ] with 2 generators>
gap> Ai4 := FR2AutomGrp(i4);
< 1, s, f >
gap> Display(Ai4);
< 1 = (1, 1), 
  s = (1, 1)(1,2), 
  f = (s, f)[1,1] >

# doc/../gap/convertersfr.gd:40-60
gap> S := FRGroup("a=<a*b^-2,b^3>(1,2)","b=<b^-1*a,1>");
<state-closed group over [ 1 .. 2 ] with 2 generators>
gap> AS := FR2AutomGrp(S);
< a, b >
gap> Display(AS);
< a = (a*b^-2, b^3)(1,2), 
  b = (b^-1*a, 1) >
gap> AssignGeneratorVariables(S);
#I  Global variable `a' is already defined and will be overwritten
#I  Global variable `b' is already defined and will be overwritten
#I  Assigned the global variables [ "a", "b" ]
gap> x := a^3*b*a^-2;
<2|a^3*b*a^-2>
gap> DecompositionOfFRElement(x);
[ [ <2|a*b^-2>, <2|b^3*a^2*b^-1*a^-1> ], [ 2, 1 ] ]
gap> y := FR2AutomGrp(x);
a^3*b*a^-2
gap> Decompose(y);
(a*b^-2, b^3*a^2*b^-1*a^-1)(1,2)

# doc/../gap/convertersfr.gd:80-89
gap> G:=AutomatonGroup("a=(b,a)(1,2),b=(a,b)");
< a, b >
gap> FG := AutomGrp2FR(G);
<state-closed group over [ 1 .. 2 ] with 2 generators>
gap> DecompositionOfFRElement(FG.1);
[ [ <2|b>, <2|a> ], [ 2, 1 ] ]
gap> DecompositionOfFRElement(FG.2);
[ [ <2|a>, <2|b> ], [ 1, 2 ] ]

# doc/../gap/convertersfr.gd:90-97
gap> G := SelfSimilarGroup("a=(a*b^-2,b)(1,2),b=(b^2,a*b*a^-2)");
< a, b >
gap> F := AutomGrp2FR(G);
<state-closed group over [ 1 .. 2 ] with 2 generators>
gap> DecompositionOfFRElement(F.1);
[ [ <2|a*b^-2>, <2|b> ], [ 2, 1 ] ]

# doc/../gap/convertersfr.gd:98-107
gap> G := AutomatonGroup("a=(b,a)(1,2),b=(a,b),c=(c,a)(1,2)");
< a, b, c >
gap> H := Group([a*b,b*c^-2,a]);
< a*b, b*c^-2, a >
gap> FH := AutomGrp2FR(H);
<recursive group over [ 1 .. 2 ] with 3 generators>
gap> DecompositionOfFRElement(FH.1);
[ [ <2|b^2>, <2|a^2> ], [ 2, 1 ] ]

# doc/../gap/convertersfr.gd:108-115
gap> G := SelfSimilarSemigroup("a=(a*b^2,b*a)[1,1],b=(b,a*b*a)(1,2)");
< a, b >
gap> S := AutomGrp2FR(G);
<state-closed semigroup over [ 1 .. 2 ] with 2 generators>
gap> DecompositionOfFRElement(S.1);
[ [ <2|a*b^2>, <2|b*a> ], [ 1, 1 ] ]

# doc/../gap/convertersfr.gd:116-125
gap> G := AutomatonGroup("a=(b,a)(1,2),b=(a,b),c=(c,a)(1,2)");
< a, b, c >
gap> Decompose(a*b^-2);
(b^-1, a^-1)(1,2)
gap> x := AutomGrp2FR(a*b^-2);
<2|a*b^-2>
gap> DecompositionOfFRElement(x);
[ [ <2|b^-1>, <2|a^-1> ], [ 2, 1 ] ]

# doc/../gap/selfs.gd:518-523
gap> NumberOfVertex([1,2,1,2], 2);
6
gap> NumberOfVertex("333", 3);
27

# doc/../gap/selfs.gd:542-547
gap> VertexNumber(1, 3, 2);
[ 1, 1, 1 ]
gap> VertexNumber(4, 4, 3);
[ 1, 1, 2, 1 ]

# doc/misc.xml:18-21
gap> G:=AG_Groups.GrigorchukGroup;
< a, b, c, d >

# doc/misc.xml:23-32
gap> AssignGeneratorVariables(G);
#I  Global variable `a' is already defined and will be overwritten
#I  Global variable `b' is already defined and will be overwritten
#I  Global variable `c' is already defined and will be overwritten
#I  Global variable `d' is already defined and will be overwritten
#I  Assigned the global variables [ a, b, c, d ]
gap> Decompose(a*b);
(c, a)(1,2)

#
gap> STOP_TEST("automgrp05.tst", 1);
