#############################################################################
##
#W  agroup.gd               automata package                   Yevgen Muntyan
##
##  automata v0.9, started 01/22/2004
##
##	Declarations of functions dealing with AGroup's
##

###############################################################################
##
#C  IsAGroup
##
DeclareCategory("IsAGroup", IsAutomObj);


###############################################################################
##
#O  AGroup(<gens>)
##
##	Creates AGroup generated by <gens>
##
DeclareOperation("AGroup", [IsList]);


###############################################################################
##
#A  StabilizerOfFirstLevel
#O  StabilizerOfLevel
#A  StabilizerOfVertex
##
DeclareAttribute("StabilizerOfFirstLevel", IsAGroup);
DeclareOperation("StabilizerOfLevel", [IsAGroup, IsInt]);
DeclareOperation("StabilizerOfVertex", [IsAGroup, IsInt]);


###############################################################################
##
#O  IndexInFreeGroup(<automata_group>)
##
DeclareOperation("IndexInFreeGroup", [IsAGroup]);


###############################################################################
##
#O  Mihaylov(<object>)
##
DeclareOperation("Mihaylov", [IsAGroup]);


###############################################################################
##
#P  IsActingOnBinaryTree
##
DeclareProperty("IsActingOnBinaryTree", IsAGroup);

















































