#############################################################################
##
#W  automsg.gd               automgrp package                  Yevgen Muntyan
#W                                                             Dmytro Savchuk
##
#Y  Copyright (C) 2003 - 2018 Yevgen Muntyan, Dmytro Savchuk
##


#############################################################################
##
#C  IsAutomSemigroup( <G> )
##
##  <#GAPDoc Label="IsAutomSemigroup">
##  <ManSection>
##  <Filt Name="IsAutomSemigroup" Arg="G" Type="Category"/>
##  <Description>
##  Whether semigroup <A>G</A> is generated by elements from category IsAutom.
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
DeclareSynonym("IsAutomSemigroup", IsSemigroup and IsAutomCollection);


#############################################################################
##
#O  AutomatonSemigroup( <string>[, <bind_vars>] )
#O  AutomatonSemigroup( <list>[, <names>, <bind_vars>] )
#O  AutomatonSemigroup( <automaton>[, <bind_vars>] )
##
##  <#GAPDoc Label="AutomatonSemigroup">
##  <ManSection>
##  <Oper Name="AutomatonSemigroup" Arg="string[, bind_vars]"/>
##  <Oper Name="AutomatonSemigroup" Label="for a list" Arg="list[, names, bind_vars]"/>
##  <Oper Name="AutomatonSemigroup" Label="for an automaton" Arg="automaton[, bind_vars]"/>
##  <Description>
##  Creates the semigroup generated by the finite automaton, described by <A>string</A>
##  or <A>list</A>, or by the argument <A>automaton</A>.
##  <P/>
##  The argument <A>string</A> is a conventional notation of the form
##  <C>name1=(name11,name12,...,name1d)trans1, name2=...</C>
##  where each <C>name*</C> is a name of a state or <C>1</C>, and each <C>trans*</C> is either a
##  permutation written in &GAP; notation, or a list defining a transformation
##  of the alphabet via <C>Transformation(trans*)</C>. Trivial permutations may be
##  omitted. This function ignores whitespace, and states may be separated
##  by commas or semicolons.
##  <P/>
##  The argument <A>list</A> is a list consisting of <M>n</M> entries corresponding to <M>n</M> states of the automaton.
##  Each entry is of the form <M>[a_1,...,a_d,p]</M>,
##  where <M>d \geq 2</M> is the size of the alphabet the group acts on, <M>a_i</M> are <C>IsInt</C> in
##  <M>\{1,\ldots,n\}</M> and
##  represent the sections of the corresponding state at all vertices of the first level of the tree;
##  and <M>p</M> is a transformation of the alphabet describing the action of the corresponding
##  state on the alphabet.
##  <P/>
##  The optional arguments <A>names</A> and <A>bind_vars</A> have the same meaning as in <Ref Func="AutomatonGroup"/>.
##  <Example><![CDATA[
##  gap> AutomatonSemigroup("a=(a, b)[2,2], b=(a,b)(1,2)");
##  < a, b >
##  gap> AutomatonSemigroup("a=(b,a,1)[1,1,3], b=(1,a,b)(1,2,3)");
##  < 1, a, b >
##  gap> A := MealyAutomaton("f0=(f0,f0)(1,2), f1=(f1,f0)[2,2]");
##  <automaton>
##  gap> G := AutomatonSemigroup(A);
##  < f0, f1 >
##  ]]></Example>
##  In the second form of this operation the definition of the second semigroup
##  looks like
##  <Example><![CDATA[
##  gap> AutomatonSemigroup([ [1,2,Transformation([2,2])], [ 1,2,(1,2)] ], ["a","b"]);
##  < a, b >
##  ]]></Example>
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
DeclareOperation("AutomatonSemigroup", [IsList]);
DeclareOperation("AutomatonSemigroup", [IsMealyAutomaton]);
DeclareOperation("AutomatonSemigroup", [IsList, IsList]);


# #############################################################################
# ##
# #O  AutomSemigroupNoBindGlobal( <list>[, <names>] )
# #O  AutomSemigroupNoBindGlobal( <string> )
# #O  AutomSemigroupNoBindGlobal( <automaton> )
# ##
# ##  These three do the same thing as AutomatonSemigroup, except they do not assign
# ##  generators of the group to variables.
# ##  \beginexample
# ##  gap> AutomSemigroupNoBindGlobal("t = (1, t)(1,2)");;
# ##  gap> t;
# ##  Variable: 't' must have a value
# ##
# ##  gap> AutomatonSemigroup("t = (1, t)(1,2)");;
# ##  gap> t;
# ##  t
# ##  \endexample
# ##
DeclareOperation("AutomatonSemigroup", [IsList, IsBool]);
DeclareOperation("AutomatonSemigroup", [IsMealyAutomaton, IsBool]);
DeclareOperation("AutomatonSemigroup", [IsList, IsList, IsBool]);


#############################################################################
##
#A  UnderlyingAutomFamily( <G> )
##
##  <#GAPDoc Label="UnderlyingAutomFamily">
##  <ManSection>
##  <Attr Name="UnderlyingAutomFamily" Arg="G"/>
##  <Description>
##  Returns the family to which the elements of <A>G</A> belong.
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
DeclareAttribute("UnderlyingAutomFamily", IsAutomCollection);
InstallSubsetMaintenance(UnderlyingAutomFamily, IsCollection, IsCollection);


#############################################################################
##
#A  UnderlyingFreeGenerators(<G>)
#A  UnderlyingFreeMonoid(<G>)
#A  UnderlyingFreeGroup(<G>)
##
##  <#GAPDoc Label="automsg:UnderlyingFreeGenerators">
##  <ManSection>
##  <Attr Name="UnderlyingFreeGenerators" Arg="G"/>
##  <Attr Name="UnderlyingFreeMonoid" Arg="G"/>
##  <Attr Name="UnderlyingFreeGroup" Arg="G"/>
##  <Description>
##
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
DeclareAttribute("UnderlyingFreeGenerators", IsAutomSemigroup, "mutable");
DeclareAttribute("UnderlyingFreeMonoid", IsAutomSemigroup);
DeclareAttribute("UnderlyingFreeGroup", IsAutomSemigroup);


#############################################################################
##
#A  UnderlyingAutomaton(<G>)
##
##  <#GAPDoc Label="UnderlyingAutomaton">
##  <ManSection>
##  <Attr Name="UnderlyingAutomaton" Arg="G"/>
##  <Description>
##  For a group (or semigroup) <A>G</A> returns an automaton generating a
##  self-similar group (or semigroup) containing <A>G</A>.
##  <Example><![CDATA[
##  gap> GS := AutomatonSemigroup("x=(x,y)[1,1], y=(y,y)(1,2)");
##  < x, y >
##  gap> A := UnderlyingAutomaton(GS);
##  <automaton>
##  gap> Display(A);
##  a1 = (a1, a2)[ 1, 1 ], a2 = (a2, a2)[ 2, 1 ]
##  ]]></Example>
##  For a subgroup of Basilica group we get the automaton generating Basilica group.
##  <Example><![CDATA[
##  gap> H := Group([u*v^-1,v^2]);
##  < u*v^-1, v^2 >
##  gap> Display(UnderlyingAutomaton(H));
##  a1 = (a1, a1), a2 = (a3, a1)(1,2), a3 = (a2, a1)
##  ]]></Example>
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
DeclareAttribute("UnderlyingAutomaton", IsAutomSemigroup);


# XXX

###############################################################################
##
#A  AutomatonList(<G>)
##
##  <#GAPDoc Label="automsg:AutomatonList">
##  <ManSection>
##  <Attr Name="AutomatonList" Label="for tree homomorphism (semi)group" Arg="G"/>
##  <Description>
##  Returns an <C>AutomatonList</C> of <C>UnderlyingAutomaton</C>(<A>G</A>) (see <Ref Func="UnderlyingAutomaton"/>).
##  <Example><![CDATA[
##  gap> Basilica := AutomatonGroup( "u=(v,1)(1,2), v=(u,1)" );
##  < u, v >
##  gap> AutomatonList(Basilica);
##  [ [ 2, 5, (1,2) ], [ 1, 5, () ], [ 5, 4, (1,2) ], [ 3, 5, () ], [ 5, 5, () ] ]
##  ]]></Example>
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
DeclareAttribute("AutomatonList", IsAutomSemigroup, "mutable");
DeclareAttribute("GeneratingAutomatonList", IsAutomSemigroup, "mutable");


#############################################################################
##
#P  IsAutomatonSemigroup (<G>)
##
##  <#GAPDoc Label="IsAutomatonSemigroup">
##  <ManSection>
##  <Prop Name="IsAutomatonSemigroup" Arg="G"/>
##  <Description>
##  is <K>true</K> if <A>G</A> is created using the command <Ref Func="AutomatonSemigroup"/>
##  and <K>false</K> otherwise.
##  To test whether <A>G</A> is self-similar use <Ref Func="IsSelfSimilar"/> command.
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
DeclareProperty("IsAutomatonSemigroup", IsAutomSemigroup);

#############################################################################
##
#A  SemigroupOfAutomFamily(<G>)
##
##  <#GAPDoc Label="SemigroupOfAutomFamily">
##  <ManSection>
##  <Attr Name="SemigroupOfAutomFamily" Arg="G"/>
##  <Description>
##
##  </Description>
##  </ManSection>
##  <#/GAPDoc>

DeclareAttribute("SemigroupOfAutomFamily", IsAutomSemigroup);


#E
