#############################################################################
##
#W  selfsimsg.gd             automgrp package                  Yevgen Muntyan
#W                                                             Dmytro Savchuk
##
#Y  Copyright (C) 2003 - 2018 Yevgen Muntyan, Dmytro Savchuk
##


#############################################################################
##
#C  IsSelfSimSemigroup( <G> )
##
##  <#GAPDoc Label="IsSelfSimSemigroup">
##  <ManSection>
##  <Filt Name="IsSelfSimSemigroup" Arg="G" Type="Category"/>
##  <Description>
##  Whether semigroup <A>G</A> is generated by elements from category IsSelfSim.
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
DeclareSynonym("IsSelfSimSemigroup", IsSemigroup and IsSelfSimCollection);


#############################################################################
##
#O  SelfSimilarSemigroup( <string>[, <bind_vars>] )
#O  SelfSimilarSemigroup( <list>[, <names>, <bind_vars>] )
#O  SelfSimilarSemigroup( <automaton>[, <bind_vars>] )
##
##  <#GAPDoc Label="SelfSimilarSemigroup">
##  <ManSection>
##  <Oper Name="SelfSimilarSemigroup" Arg="string[, bind_vars]"/>
##  <Oper Name="SelfSimilarSemigroup" Label="for a list" Arg="list[, names, bind_vars]"/>
##  <Oper Name="SelfSimilarSemigroup" Label="for an automaton" Arg="automaton[, bind_vars]"/>
##  <Description>
##  Creates the semigroup generated by the wreath recursion, described by <A>string</A>
##  or <A>list</A>, or given by the argument <A>automaton</A>. Note, that on the contrary to
##  <Ref Func="AutomatonSemigroup"/> in some cases the defined semigroup
##  may not be self-similar, since the sections of generators may include inverses of
##  generators or trivial homomorphisms, not included in the semigroup generated by the
##  generators. If one needs to have self-similarity it is always possible to include the
##  necessary sections in the generating set.
##  <P/>
##  The argument <A>string</A> is a conventional notation of the form
##  <C>name1=(word11,word12,...,word1d)trans1, name2=...</C>
##  where each <C>name*</C> is a name of a state, <C>word*</C> is an associative word
##  over the alphabet consisting of all <C>name*</C>, and each <C>trans*</C> is either a
##  permutation written in &GAP; notation, or a list defining a transformation
##  of the alphabet via <C>Transformation(trans*)</C>. Trivial permutations may be
##  omitted. This function ignores whitespace, and states may be separated
##  by commas or semicolons.
##  <P/>
##  The argument <A>list</A> is a list consisting of <M>n</M> entries corresponding to <M>n</M> generators of the semigroup.
##  Each entry is of the form <M>[a_1,...,a_d,p]</M>,
##  where <M>d \geq 2</M> is the size of the alphabet the semigroup acts on, <M>a_i</M> are lists
##  acceptable by <C>AssocWordByLetterRep</C> (e.g. if the names of generators are <C>x</C>, <C>y</C> and <C>z</C>,
##  then <C>[1, 1, 2, 3]</C> will produce <C>x^2*y*z</C>)
##  representing the sections of the corresponding generator at all vertices of the first level of the tree;
##  and <M>p</M> is a transformation of the alphabet describing the action of the corresponding
##  generator.
##  <P/>
##  The optional arguments <A>names</A> and <A>bind_vars</A> have the same meaning as in <Ref Func="SelfSimilarGroup"/>.
##  <Example><![CDATA[
##  gap> SelfSimilarSemigroup("a=(a*b,b)[1,1], b=(a,b^2*a)(1,2)");
##  < a, b >
##  gap> SelfSimilarSemigroup("a=(b,a,a^3)(2,3), b=(1,a*b,b^-1)(1,2,3)");
##  < a, b >
##  gap> A := MealyAutomaton("f0=(f0,f0)(1,2), f1=(f1,f0)[2,2]");
##  <automaton>
##  gap> SelfSimilarSemigroup(A);
##  < f0, f1 >
##  ]]></Example>
##  In the second form of this operation the definition of the first semigroup
##  looks like
##  <Example><![CDATA[
##  gap> SelfSimilarSemigroup([[[1,2], [2], ()], [[1], [2,2,1], (1,2)]],["a","b"]);
##  < a, b >
##  ]]></Example>
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
DeclareOperation("SelfSimilarSemigroup", [IsList]);
DeclareOperation("SelfSimilarSemigroup", [IsList, IsList]);
DeclareOperation("SelfSimilarSemigroup", [IsMealyAutomaton]);
DeclareOperation("SelfSimilarSemigroup", [IsList, IsBool]);
DeclareOperation("SelfSimilarSemigroup", [IsList, IsList, IsBool]);
DeclareOperation("SelfSimilarSemigroup", [IsMealyAutomaton, IsBool]);


#############################################################################
##
#A  UnderlyingSelfSimFamily( <G> )
##
##  <#GAPDoc Label="UnderlyingSelfSimFamily">
##  <ManSection>
##  <Attr Name="UnderlyingSelfSimFamily" Arg="G"/>
##  <Description>
##  Returns the family to which elements of <A>G</A> belong.
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
DeclareAttribute("UnderlyingSelfSimFamily", IsSelfSimCollection);
InstallSubsetMaintenance(UnderlyingSelfSimFamily, IsCollection, IsCollection);


#############################################################################
##
#A  UnderlyingFreeGenerators(<G>)
#A  UnderlyingFreeMonoid(<G>)
#A  UnderlyingFreeGroup(<G>)
##
##  <#GAPDoc Label="selfsimsg:UnderlyingFreeGenerators">
##  <ManSection>
##  <Attr Name="UnderlyingFreeGenerators" Arg="G"/>
##  <Attr Name="UnderlyingFreeMonoid" Arg="G"/>
##  <Attr Name="UnderlyingFreeGroup" Arg="G"/>
##  <Description>
##
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
DeclareAttribute("UnderlyingFreeGenerators", IsSelfSimSemigroup, "mutable");
DeclareAttribute("UnderlyingFreeMonoid", IsSelfSimSemigroup);
DeclareAttribute("UnderlyingFreeGroup", IsSelfSimSemigroup);


###############################################################################
##
#A  RecurList(<G>)
##
##  <#GAPDoc Label="RecurList">
##  <ManSection>
##  <Attr Name="RecurList" Label="for tree homomorphism (semi)group" Arg="G"/>
##  <Description>
##  Returns an internal representation of the wreath recursion of the
##  self-similar group (semigroup) containing <A>G</A>.
##  <Example><![CDATA[
##  gap> R := SelfSimilarGroup("a=(a^-1*b,b^-1*a)(1,2), b=(a^-1,b^-1)");
##  < a, b >
##  gap> RecurList(R);
##  [ [ [ -1, 2 ], [ -2, 1 ], (1,2) ], [ [ -1 ], [ -2 ], () ], 
##    [ [ -1, 2 ], [ -2, 1 ], (1,2) ], [ [ 1 ], [ 2 ], () ] ]
##  ]]></Example>
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
DeclareAttribute("RecurList", IsSelfSimSemigroup, "mutable");

DeclareAttribute("GeneratingRecurList", IsSelfSimSemigroup, "mutable");




#############################################################################
##
#P  IsSemigroupOfSelfSimFamily( <G> )
##
##  <#GAPDoc Label="IsSemigroupOfSelfSimFamily">
##  <ManSection>
##  <Prop Name="IsSemigroupOfSelfSimFamily" Arg="G"/>
##  <Description>
##  Whether semigroup <A>G</A> is the whole semigroup generated by the automaton used to
##  construct elements of <A>G</A>.
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
DeclareProperty("IsSemigroupOfSelfSimFamily", IsSelfSimSemigroup);
InstallTrueMethod(IsSelfSimilar, IsSemigroupOfSelfSimFamily);



#############################################################################
##
#P  IsSelfSimilarSemigroup (<G>)
##
##  <#GAPDoc Label="IsSelfSimilarSemigroup">
##  <ManSection>
##  <Prop Name="IsSelfSimilarSemigroup" Arg="G"/>
##  <Description>
##  is <K>true</K> if <A>G</A> is created using the command <Ref Func="SelfSimilarSemigroup"/>
##  or if generators of <A>G</A> coincide with generators of corresponding family, and <K>false</K> otherwise.
##  To test whether <A>G</A> is self-similar use <Ref Func="IsSelfSimilar"/> command.
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
DeclareProperty("IsSelfSimilarSemigroup", IsSelfSimSemigroup);
InstallTrueMethod(IsSemigroupOfSelfSimFamily, IsSelfSimilarSemigroup);


#############################################################################
##
#P  IsFiniteState (<G>)
##
##  <#GAPDoc Label="selfsimsg:IsFiniteState">
##  <ManSection>
##  <Prop Name="IsFiniteState" Label="for tree homomorphism (semi)group" Arg="G"/>
##  <Description>
##  For a group or semigroup of homomorphisms of the tree defined using a
##  wreath recursion, returns <K>true</K> if all
##  generators can be represented as finite automata (have finitely many different
##  sections).
##  It will never stop if the free reduction of words is not sufficient to establish
##  the finite-state property or if the group is not finite-state.
##  In case <A>G</A> is a finite-state group it automatically computes the attributes
##  <C>UnderlyingAutomatonGroup</C>(<A>G</A>) (<Ref Func="UnderlyingAutomatonGroup"/>),
##  <C>IsomorphicAutomGroup</C>(<A>G</A>) (<Ref Func="IsomorphicAutomGroup"/>) and
##  <C>MonomorphismToAutomatonGroup</C>(<A>G</A>) (<Ref Func="MonomorphismToAutomatonGroup"/>).
##  For a finite-state semigroup it computes the corresponding attributes
##  <C>UnderlyingAutomatonSemigroup</C>(<A>G</A>) (<Ref Func="UnderlyingAutomatonSemigroup"/>),
##  <C>IsomorphicAutomSemigroup</C>(<A>G</A>) (<Ref Func="IsomorphicAutomSemigroup"/>) and
##  <C>MonomorphismToAutomatonSemigroup</C>(<A>G</A>) (<Ref Func="MonomorphismToAutomatonSemigroup"/>).
##  <Example><![CDATA[
##  gap> W := SelfSimilarGroup("x=(x^-1,y)(1,2), y=(z^-1,1)(1,2), z=(1,x*y)");
##  < x, y, z >
##  gap> IsFiniteState(W);
##  true
##  gap> Size(GeneratorsOfGroup(UnderlyingAutomatonGroup(W)));
##  50
##  ]]></Example>
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
DeclareProperty("IsFiniteState", IsSelfSimSemigroup);


#############################################################################
##
#A  IsomorphicAutomSemigroup(<G>)
##
##  <#GAPDoc Label="IsomorphicAutomSemigroup">
##  <ManSection>
##  <Attr Name="IsomorphicAutomSemigroup" Arg="G"/>
##  <Description>
##  In case <A>G</A> is finite-state returns a semigroup generated by automata, isomorphic to <A>G</A>,
##  which is a subsemigroup of <C>UnderlyingAutomatonSemigroup</C>(<A>G</A>) (see <Ref Func="UnderlyingAutomatonSemigroup"/>).
##  The natural isomorphism between <A>G</A> and <C>IsomorphicAutomSemigroup</C>(<A>G</A>) is stored in the
##  attribute <C>MonomorphismToAutomatonSemigroup</C>(<A>G</A>) (<Ref Func="MonomorphismToAutomatonSemigroup"/>).
##  <Example><![CDATA[
##  gap> R := SelfSimilarSemigroup("a=(1,1)[1,1], b=(a*c,1)(1,2), c=(1,a*b)");
##  < a, b, c >
##  gap> UR := UnderlyingAutomatonSemigroup(R);
##  < 1, a1, a3, a5, a6 >
##  gap> IR := IsomorphicAutomSemigroup(R);
##  < a1, a3, a5 >
##  gap> hom := MonomorphismToAutomatonSemigroup(R);
##  MappingByFunction( < a, b, c >, < a1, a3, a5 >, function( a ) ... end, functio\
##  n( b ) ... end )
##  gap> (a*b)^hom;
##  a1*a3
##  gap> PreImagesRepresentative(hom, last);
##  a*b
##  gap> List(GeneratorsOfSemigroup(UR), x -> PreImagesRepresentative(hom, x));
##  [ 1, a, b, c, a*b ]
##  ]]></Example>
##  All these operations work also for the subsemigroups of semigroups generated by
##  <Ref Func="SelfSimilarSemigroup"/>.
##  <Example><![CDATA[
##  gap> T := Semigroup([a*b, b^2]);
##  < a*b, b^2 >
##  gap> IT := IsomorphicAutomSemigroup(T);
##  < a1, a4 >
##  ]]></Example>
##  Note, that different semigroups have different <C>UnderlyingAutomSemigroup</C> attributes. For example,
##  the generator <C>a1</C> of semigroup <C>IT</C> above is different from the generator <C>a1</C> of semigroup <C>IR</C>.
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
DeclareAttribute("IsomorphicAutomSemigroup", IsSelfSimSemigroup, "mutable");


#############################################################################
##
#A  UnderlyingAutomatonSemigroup(<G>)
##
##  <#GAPDoc Label="UnderlyingAutomatonSemigroup">
##  <ManSection>
##  <Attr Name="UnderlyingAutomatonSemigroup" Arg="G"/>
##  <Description>
##  In case <A>G</A> is finite-state returns a self-similar closure of <A>G</A> as a semigroup
##  generated by automaton.
##  The natural monomorphism from <A>G</A> to <C>UnderlyingAutomatonSemigroup</C>(<A>G</A>) is stored in the
##  attribute <C>MonomorphismToAutomatonSemigroup</C>(<A>G</A>) (<Ref Func="MonomorphismToAutomatonSemigroup"/>). If
##  <A>G</A> is created by <Ref Func="SelfSimilarSemigroup"/>, then the self-similar closure
##  of <A>G</A> coincides with <A>G</A>, so one can use <C>MonomorphismToAutomatonSemigroup</C>(<A>G</A>) to
##  get preimages of elements of <C>UnderlyingAutomatonSemigroup</C>(<A>G</A>) in <A>G</A>. See the example for
##  <Ref Func="IsomorphicAutomSemigroup"/>.
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
DeclareAttribute("UnderlyingAutomatonSemigroup", IsSelfSimSemigroup, "mutable");


#############################################################################
##
#A  MonomorphismToAutomatonSemigroup(<G>)
##
##  <#GAPDoc Label="MonomorphismToAutomatonSemigroup">
##  <ManSection>
##  <Attr Name="MonomorphismToAutomatonSemigroup" Arg="G"/>
##  <Description>
##  In case <A>G</A> is finite-state returns a monomorphism from <A>G</A> into <C>UnderlyingAutomatonSemigroup</C>(<A>G</A>)
##  (see <Ref Func="UnderlyingAutomatonSemigroup"/>). If <A>G</A> is created by <C>SelfSimilarSemigroup</C>
##  (see <Ref Func="SelfSimilarSemigroup"/>),
##  then one can use <C>MonomorphismToAutomatonSemigroup</C>(<A>G</A>) to
##  get preimages of elements of <C>UnderlyingAutomatonSemigroup</C>(<A>G</A>) in <A>G</A>. See the example for
##  <Ref Func="IsomorphicAutomSemigroup"/>.
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
DeclareAttribute("MonomorphismToAutomatonSemigroup", IsSelfSimSemigroup, "mutable");

#############################################################################
##
#A  SemigroupOfSelfSimFamily(<G>)
##
##  <#GAPDoc Label="SemigroupOfSelfSimFamily">
##  <ManSection>
##  <Attr Name="SemigroupOfSelfSimFamily" Arg="G"/>
##  <Description>
##
##  </Description>
##  </ManSection>
##  <#/GAPDoc>

DeclareAttribute("SemigroupOfSelfSimFamily", IsSelfSimSemigroup);


#E
