#############################################################################
##
#W  selfsimgroup.gd           automgrp package                 Yevgen Muntyan
#W                                                             Dmytro Savchuk
##
#Y  Copyright (C) 2003 - 2018 Yevgen Muntyan, Dmytro Savchuk
##


#############################################################################
##
#C  IsSelfSimGroup( <G> )
##
##  <#GAPDoc Label="IsSelfSimGroup">
##  <ManSection>
##  <Filt Name="IsSelfSimGroup" Arg="G" Type="Category"/>
##  <Description>
##  The category of groups whose generators are defined using wreath recursion
##  (elements from category <C>IsSelfSim</C>). These groups need not be self-similar.
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
DeclareSynonym("IsSelfSimGroup", IsSelfSimCollection and IsGroup);
InstallTrueMethod(IsTreeAutomorphismCollection, IsSelfSimGroup);
InstallTrueMethod(IsInvertibleSelfSimCollection, IsSelfSimGroup);


#############################################################################
##
#O  SelfSimilarGroup( <string>[, <bind_vars>] )
#O  SelfSimilarGroup( <list>[, <names>, <bind_vars>] )
#O  SelfSimilarGroup( <automaton>[, <bind_vars>] )
##
##  <#GAPDoc Label="SelfSimilarGroup">
##  <ManSection>
##  <Oper Name="SelfSimilarGroup" Arg="string[, bind_vars]"/>
##  <Oper Name="SelfSimilarGroup" Label="for a list" Arg="list[, names, bind_vars]"/>
##  <Oper Name="SelfSimilarGroup" Label="for an automaton" Arg="automaton[, bind_vars]"/>
##  <Description>
##  Creates the self-similar group generated by the wreath recursion, described by <A>string</A>
##  or <A>list</A>, or given by the argument <A>automaton</A>.
##  <P/>
##  The argument <A>string</A> is a conventional notation of the form
##  <C>name1=(word11,word12,...,word1d)perm1, name2=...</C>
##  where each <C>name*</C> is a name of a state, <C>word*</C> is an associative word
##  over the alphabet consisting of all <C>name*</C>, and each <C>perm*</C> is a
##  permutation written in &GAP; notation. Trivial permutations may be
##  omitted. This function ignores whitespace, and states may be separated
##  by commas or semicolons.
##  <P/>
##  The argument <A>list</A> is a list consisting of <M>n</M> entries corresponding to <M>n</M> generators of the group.
##  Each entry is of the form <M>[a_1,...,a_d,p]</M>,
##  where <M>d \geq 2</M> is the size of the alphabet the group acts on, <M>a_i</M> are lists
##  acceptable by <C>AssocWordByLetterRep</C> (e.g. if the names of generators are <C>x</C>, <C>y</C> and <C>z</C>,
##  then <C>[1, 1, -2, -2, 1, 3]</C> will produce <C>x^2*y^-2*x*z</C>)
##  representing the sections of the corresponding generator at all vertices of the first level of the tree;
##  and <M>p</M> from <C>SymmetricGroup(<A>d</A>)</C> describes the action of the corresponding generator on the
##  alphabet.
##  <P/>
##  The optional argument <A>names</A> must be a list of names of generators of the group.
##  These names are used to display the elements of the resulting group.
##  <P/>
##  If the optional argument <A>bind_vars</A> is <K>false</K> the names of generators of the group are not assigned
##  to the global variables. The default value is <K>true</K>. One can use
##  <C>AssignGeneratorVariables</C> function to assign these names later, if they were not assigned
##  when the group was created.
##  <Example><![CDATA[
##  gap> SelfSimilarGroup("a=(a*b, b^-1), b=(1, b^2*a)(1,2)");
##  < a, b >
##  gap> SelfSimilarGroup("a=(b,a,a^-1)(2,3), b=(1,a*b,b)(1,2,3)");
##  < a, b >
##  gap> A := MealyAutomaton("f0=(f0,f0)(1,2),f1=(f1,f0)");
##  <automaton>
##  gap> SelfSimilarGroup(A);
##  < f0, f1 >
##  ]]></Example>
##  In the second form of this operation the definition of the first group
##  looks like
##  <Example><![CDATA[
##  gap> SelfSimilarGroup([[ [1,2], [-2], ()], [ [], [2,2,1], (1,2) ]], ["a","b"]);
##  < a, b >
##  ]]></Example>
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
DeclareOperation("SelfSimilarGroup", [IsList]);
DeclareOperation("SelfSimilarGroup", [IsList, IsList]);
DeclareOperation("SelfSimilarGroup", [IsList, IsBool]);
DeclareOperation("SelfSimilarGroup", [IsList, IsList, IsBool]);
DeclareOperation("SelfSimilarGroup", [IsMealyAutomaton]);
DeclareOperation("SelfSimilarGroup", [IsMealyAutomaton, IsBool]);



#############################################################################
##
#P  IsGroupOfSelfSimFamily( <G> )
##
##  <#GAPDoc Label="IsGroupOfSelfSimFamily">
##  <ManSection>
##  <Prop Name="IsGroupOfSelfSimFamily" Arg="G"/>
##  <Description>
##  Whether group <A>G</A> is the whole group generated by the automaton used to
##  construct elements of <A>G</A>.
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
DeclareProperty("IsGroupOfSelfSimFamily", IsSelfSimGroup);
InstallTrueMethod(IsSelfSimilar, IsGroupOfSelfSimFamily);


#############################################################################
##
#A  UnderlyingFreeSubgroup(<G>)
##
##  <#GAPDoc Label="selfsimgroup:UnderlyingFreeSubgroup">
##  <ManSection>
##  <Attr Name="UnderlyingFreeSubgroup" Arg="G"/>
##  <Description>
##
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
DeclareAttribute("UnderlyingFreeSubgroup", IsSelfSimGroup, "mutable");


#############################################################################
##
#P  IsSelfSimilarGroup (<G>)
##
##  <#GAPDoc Label="IsSelfSimilarGroup">
##  <ManSection>
##  <Prop Name="IsSelfSimilarGroup" Arg="G"/>
##  <Description>
##  is <K>true</K> if <A>G</A> is created using the command <Ref Func="SelfSimilarGroup"/>
##  or if the generators of <A>G</A> coincide with the generators of the corresponding family, and <K>false</K> otherwise.
##  To test whether <A>G</A> is self-similar use <Ref Func="IsSelfSimilar"/> command.
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
DeclareProperty("IsSelfSimilarGroup", IsSelfSimGroup);
InstallTrueMethod(IsGroupOfSelfSimFamily, IsSelfSimilarGroup);


#############################################################################
##
#A  IsomorphicAutomGroup(<G>)
##
##  <#GAPDoc Label="IsomorphicAutomGroup">
##  <ManSection>
##  <Attr Name="IsomorphicAutomGroup" Arg="G"/>
##  <Description>
##  In case <A>G</A> is finite-state tries to compute a group generated by automata, isomorphic to <A>G</A>,
##  which is a subgroup of <C>UnderlyingAutomatonGroup</C>(<A>G</A>) (see <Ref Func="UnderlyingAutomatonGroup"/>).
##  The natural isomorphism between <A>G</A> and <C>IsomorphicAutomGroup</C>(<A>G</A>) is stored in the
##  attribute <C>MonomorphismToAutomatonGroup</C>(<A>G</A>) (<Ref Func="MonomorphismToAutomatonGroup"/>).
##  In some cases it may be useful to check if <A>G</A> is finite.
##  <Example><![CDATA[
##  gap> R := SelfSimilarGroup("a=(a^-1*b,b^-1*a)(1,2), b=(a^-1,b^-1)");
##  < a, b >
##  gap> UR := UnderlyingAutomatonGroup(R);
##  < a1, a2, a4, a5 >
##  gap> IR := IsomorphicAutomGroup(R);
##  < a1, a5 >
##  gap> hom := MonomorphismToAutomatonGroup(R);
##  MappingByFunction( < a, b >, < a1, a5 >, function( a ) ... end, function( b ) \
##  ... end )
##  gap> (a*b)^hom;
##  a1*a5
##  gap> PreImagesRepresentative(hom, last);
##  a*b
##  gap> List(GeneratorsOfGroup(UR), x -> PreImagesRepresentative(hom, x));
##  [ a, a^-1*b, b^-1*a, b ]
##  ]]></Example>
##  All these operations work also for the subgroups of groups generated by <C>SelfSimilarGroup</C>.
##  (<Ref Func="SelfSimilarGroup"/>).
##  <Example><![CDATA[
##  gap> T := Group([b*a, a*b]);
##  < b*a, a*b >
##  gap> IT := IsomorphicAutomGroup(T);
##  < a1, a4 >
##  ]]></Example>
##  Note, that different groups have different <C>UnderlyingAutomGroup</C> attributes. For example,
##  the generator <C>a1</C> of group <C>IT</C> above is different from the generator <C>a1</C> of group <C>IR</C>.
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
DeclareAttribute("IsomorphicAutomGroup", IsSelfSimGroup, "mutable");


#############################################################################
##
#A  UnderlyingAutomatonGroup(<G>)
##
##  <#GAPDoc Label="UnderlyingAutomatonGroup">
##  <ManSection>
##  <Attr Name="UnderlyingAutomatonGroup" Arg="G"/>
##  <Description>
##  In case <A>G</A> is finite-state returns a self-similar closure of <A>G</A> as a group
##  generated by automaton.
##  The natural monomorphism from <A>G</A> and <C>UnderlyingAutomatonGroup</C>(<A>G</A>) is stored in the
##  attribute <C>MonomorphismToAutomatonGroup</C>(<A>G</A>) (<Ref Func="MonomorphismToAutomatonGroup"/>). If
##  <A>G</A> is created by <Ref Func="SelfSimilarGroup"/>, then the self-similar closure
##  of <A>G</A> coincides with <A>G</A>, so one can use <C>MonomorphismToAutomatonGroup</C>(<A>G</A>) to
##  get preimages of elements of <C>UnderlyingAutomatonGroup</C>(<A>G</A>) in <A>G</A>. See the example for
##  <Ref Func="IsomorphicAutomGroup"/>.
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
DeclareAttribute("UnderlyingAutomatonGroup", IsSelfSimGroup, "mutable");


#############################################################################
##
#A  MonomorphismToAutomatonGroup(<G>)
##
##  <#GAPDoc Label="MonomorphismToAutomatonGroup">
##  <ManSection>
##  <Attr Name="MonomorphismToAutomatonGroup" Arg="G"/>
##  <Description>
##  In case <A>G</A> is finite-state returns a monomorphism from <A>G</A> into <C>UnderlyingAutomatonGroup</C>(<A>G</A>)
##  (see <Ref Func="UnderlyingAutomatonGroup"/>). If <A>G</A> is created by <Ref Func="SelfSimilarGroup"/>,
##  then one can use <C>MonomorphismToAutomatonGroup</C>(<A>G</A>) to
##  get preimages of elements of <C>UnderlyingAutomatonGroup</C>(<A>G</A>) in <A>G</A>. See the example for
##  <Ref Func="IsomorphicAutomGroup"/>.
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
DeclareAttribute("MonomorphismToAutomatonGroup", IsSelfSimGroup, "mutable");


#############################################################################
##
#A  GroupOfSelfSimFamily(<G>)
##
##  <#GAPDoc Label="selfsimgroup:GroupOfSelfSimFamily">
##  <ManSection>
##  <Attr Name="GroupOfSelfSimFamily" Arg="G"/>
##  <Description>
##
##  </Description>
##  </ManSection>
##  <#/GAPDoc>

DeclareAttribute("GroupOfSelfSimFamily", IsSelfSimGroup);

#E
