#############################################################################
##
#W  treehomsg.gd             automgrp package                  Yevgen Muntyan
#W                                                             Dmytro Savchuk
##
#Y  Copyright (C) 2003 - 2018 Yevgen Muntyan, Dmytro Savchuk
##


###############################################################################
##
#C  IsTreeHomomorphismSemigroup
##
##  <#GAPDoc Label="IsTreeHomomorphismSemigroup">
##  <ManSection>
##  <Filt Name="IsTreeHomomorphismSemigroup" Arg="" Type="Category"/>
##  <Description>
##  Category of semigroups of tree homomorphisms.
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
DeclareSynonym("IsTreeHomomorphismSemigroup", IsSemigroup and IsTreeHomomorphismCollection);
InstallTrueMethod(IsActingOnTree, IsTreeHomomorphismSemigroup);


###############################################################################
##
#P  IsSelfSimilar (<G>)
##
##  <#GAPDoc Label="IsSelfSimilar">
##  <ManSection>
##  <Prop Name="IsSelfSimilar" Arg="G"/>
##  <Description>
##  Returns whether the group or semigroup <A>G</A> is self-similar (see <Ref Sect="Short math background"/>).
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
DeclareProperty("IsSelfSimilar", IsTreeHomomorphismSemigroup and IsActingOnRegularTree);
DeclareFilter("CanEasilyTestSelfSimilarity");
InstallTrueMethod(CanEasilyTestSelfSimilarity, HasIsSelfSimilar);


#############################################################################
##
#P  IsSphericallyTransitive (<G>)
##
##  <#GAPDoc Label="treehomsg:IsSphericallyTransitive">
##  <ManSection>
##  <Prop Name="IsSphericallyTransitive" Label="for tree homomorphism (semi)group" Arg="G"/>
##  <Description>
##  Returns whether the group <A>G</A> is spherically transitive (see&nbsp;<Ref Sect="Short math background"/>).
##  <Example><![CDATA[
##  gap> Grigorchuk_Group := AutomatonGroup("a=(1,1)(1,2),b=(a,c),c=(a,d),d=(1,b)");
##  < a, b, c, d >
##  gap> IsSphericallyTransitive(Grigorchuk_Group);
##  true
##  ]]></Example>
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
DeclareProperty("IsSphericallyTransitive", IsTreeHomomorphismSemigroup);


#############################################################################
##
#O  IsTransitiveOnLevel (<G>, <lev>)
##
##  <#GAPDoc Label="treehomsg:IsTransitiveOnLevel">
##  <ManSection>
##  <Oper Name="IsTransitiveOnLevel" Label="for tree homomorphism (semi)group" Arg="G, lev"/>
##  <Description>
##  Returns whether the group (semigroup) <A>G</A> acts transitively on level <A>lev</A>.
##  <Example><![CDATA[
##  gap> Grigorchuk_Group := AutomatonGroup("a=(1,1)(1,2),b=(a,c),c=(a,d),d=(1,b)");
##  < a, b, c, d >
##  gap> IsTransitiveOnLevel(Group([a,b]),3);
##  true
##  gap> IsTransitiveOnLevel(Group([a,b]),4);
##  false
##  ]]></Example>
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
DeclareOperation("IsTransitiveOnLevel", [IsTreeHomomorphismSemigroup, IsPosInt]);


###############################################################################
##
#O  TransformationSemigroupOnLevel (<G>, <k>)
##
##  <#GAPDoc Label="TransformationSemigroupOnLevel">
##  <ManSection>
##  <Oper Name="TransformationSemigroupOnLevel" Arg="G, k"/>
##  <Description>
##  Returns the semigroup of transformations induced by the action of the semigroup <A>G</A> at the <A>k</A>-th
##  level.
##  <Example><![CDATA[
##  gap> S := AutomatonSemigroup("y=(1,u)[1,1],u=(y,u)(1,2)");
##  < 1, y, u >
##  gap> T := TransformationSemigroupOnLevel(S,3);
##  <transformation monoid of degree 8 with 2 generators>
##  gap> Size(T);
##  11
##  ]]></Example>
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
KeyDependentOperation("TransformationSemigroupOnLevel", IsTreeHomomorphismSemigroup, IsPosInt, ReturnTrue);


#############################################################################
##
#O  MarkovOperator( <G>, <lev>, <weights> )
##
##  <#GAPDoc Label="MarkovOperator">
##  <ManSection>
##  <Oper Name="MarkovOperator" Arg="G, lev, weights"/>
##  <Description>
##  Computes the matrix of the Markov operator related to the (semi)group <A>G</A> on the <A>lev</A>-th level
##  of the tree. If <A>G</A> is a group generated by <M>g_1,g_2,\ldots,g_n</M>, then the Markov operator
##  is defined as <M>(\mathrm{PermOnLevelAsMatrix}(g_1)+\cdots+\mathrm{PermOnLevelAsMatrix}(g_n)+
##  \mathrm{PermOnLevelAsMatrix}(g_1^{-1})+\cdots+\mathrm{PermOnLevelAsMatrix}(g_n^{-1}))/(2*n)</M>.
##  If <A>S</A> is a semigroup generated by <M>s_1,s_2,\ldots,s_n</M>, then the Markov operator
##  is defined similarly with <C>PermOnLevelAsMatrix</C> being replaced with <C>TransformationOnLevelAsMatrix</C>.
##  If the list of <A>weights</A> is given, uses its entries as coefficients of operators corresponding to
##  the generators of a group or semigroup. In the case of a group, the length of <A>weights</A> must be twice
##  as big as the number of generators of <A>G</A>. The list <A>weights</A> may consist either of numbers or of strings
##  representing the names of indeterminates.
##  See also
##  <Ref Func="PermOnLevelAsMatrix"/> and <Ref Func="TransformationOnLevelAsMatrix"/>.
##  <Example><![CDATA[
##  gap> L := AutomatonGroup("p=(p,q)(1,2), q=(p,q)");
##  < p, q >
##  gap> MarkovOperator(L, 3);
##  [ [ 0, 0, 1/4, 1/4, 0, 1/4, 0, 1/4 ], [ 0, 0, 1/4, 1/4, 1/4, 0, 1/4, 0 ], 
##    [ 1/4, 1/4, 0, 0, 1/4, 0, 1/4, 0 ], [ 1/4, 1/4, 0, 0, 0, 1/4, 0, 1/4 ], 
##    [ 0, 1/4, 1/4, 0, 0, 1/2, 0, 0 ], [ 1/4, 0, 0, 1/4, 1/2, 0, 0, 0 ], 
##    [ 0, 1/4, 1/4, 0, 0, 0, 1/2, 0 ], [ 1/4, 0, 0, 1/4, 0, 0, 0, 1/2 ] ]
##  gap> MarkovOperator(L,3,["a","b","c","d"]);
##  [ [ 0, 0, d, b, 0, c, 0, a ], [ 0, 0, b, d, c, 0, a, 0 ], 
##    [ b, d, 0, 0, a, 0, c, 0 ], [ d, b, 0, 0, 0, a, 0, c ], 
##    [ 0, a, c, 0, 0, b+d, 0, 0 ], [ a, 0, 0, c, b+d, 0, 0, 0 ], 
##    [ 0, c, a, 0, 0, 0, b+d, 0 ], [ c, 0, 0, a, 0, 0, 0, b+d ] ]
##  ]]></Example>
##  In the case of semigroups we have:
##  <Example><![CDATA[
##  gap> S := AutomatonSemigroup("c=(c,d)[1,1],d=(c,c)(1,2)");
##  < c, d >
##  gap> MarkovOperator(S,3,["w1","w2"]);
##  [ [ w1, 0, 0, 0, w2, 0, 0, 0 ], [ w1, 0, 0, 0, w2, 0, 0, 0 ], 
##    [ 0, w1, 0, 0, 0, w2, 0, 0 ], [ w1, 0, 0, 0, w2, 0, 0, 0 ], 
##    [ w2, 0, w1, 0, 0, 0, 0, 0 ], [ w2, 0, w1, 0, 0, 0, 0, 0 ], 
##    [ w1, w2, 0, 0, 0, 0, 0, 0 ], [ w1+w2, 0, 0, 0, 0, 0, 0, 0 ] ]
##  gap> MarkovOperator(S,3,[1/3,2/3]);
##  [ [ 1/3, 0, 0, 0, 2/3, 0, 0, 0 ], [ 1/3, 0, 0, 0, 2/3, 0, 0, 0 ], 
##    [ 0, 1/3, 0, 0, 0, 2/3, 0, 0 ], [ 1/3, 0, 0, 0, 2/3, 0, 0, 0 ], 
##    [ 2/3, 0, 1/3, 0, 0, 0, 0, 0 ], [ 2/3, 0, 1/3, 0, 0, 0, 0, 0 ], 
##    [ 1/3, 2/3, 0, 0, 0, 0, 0, 0 ], [ 1, 0, 0, 0, 0, 0, 0, 0 ] ]
##  ]]></Example>
##  </Description>
##  </ManSection>
##  <#/GAPDoc>

DeclareOperation("MarkovOperator", [IsTreeHomomorphismSemigroup, IsCyclotomic, IsList]);
DeclareOperation("MarkovOperator", [IsTreeHomomorphismSemigroup, IsCyclotomic]);


###############################################################################
##
#O  Section( <G>, <v> )
##
##  <#GAPDoc Label="treehomsg:Section">
##  <ManSection>
##  <Oper Name="Section" Arg="G, v"/>
##  <Description>
##  For a (semi)group <A>G</A> acting on a rooted tree stabilizing the vertex <A>v</A> of
##  the tree returns the (semi)group
##  generated by the sections of generators of <A>G</A> at vertex <A>v</A>. Generates error
##  if the vertex <A>v</A> is not fixed by <A>G</A>.
##  The vertex <A>v</A> can be a list representing the vertex, or a positive integer
##  representing a vertex of the first level of the tree.
##  <Example><![CDATA[
##  gap> G := AutomatonGroup("u=(v,u)(1,2),v=(u,1)");
##  < u, v >
##  gap> S := StabilizerOfVertex(G,[1,2]);
##  < u^2*v^-1, u*v*u^-1, v*u^2, v^2, u^-1*v*u >
##  gap> Section(S,[1,2]);
##  < u^2*v, u*v >
##  ]]></Example>
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
DeclareOperation("Section", [IsTreeHomomorphismSemigroup, IsList]);
DeclareOperation("Section", [IsTreeHomomorphismSemigroup, IsPosInt]);



#E
